id: A29B430E7
title: Prayer to Gyurme Tsewang Gyatso
type: translation
pechas:
- ID23C011A
- I342E284F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:59:30.571565
  last_modified_at: 2023-01-04 11:59:30.571579
  collections:
  - Gyurme Tsewang Gyatso Series
  - Works of Tibetan Masters
alignment_to_base:
  ID23C011A/3474: 5BB9
  I342E284F/CE2C: 5BB9
